name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the API Health Check Endpoint
        run: curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -s https://finansal-risk-ai.onrender.com/api/health